---
- name: Configure and run SatPing server
  hosts: satping
  become: yes

  vars:
    ecr_image: "439638384547.dkr.ecr.eu-west-3.amazonaws.com/satping:latest"
    aws_region: "eu-west-3"

  tasks:
    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Install AWS CLI
      dnf:
        name: awscli
        state: present

    - name: Login to ECR
      shell: |
        aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin 439638384547.dkr.ecr.eu-west-3.amazonaws.com
      environment:
        AWS_DEFAULT_REGION: "{{ aws_region }}"
        AWS_ACCESS_KEY_ID: "{{ aws_access_key }}"
        AWS_SECRET_ACCESS_KEY: "{{ aws_secret_key }}"

    - name: Pull SatPing image from ECR
      shell: docker pull {{ ecr_image }}

    - name: Run SatPing container
      shell: |
        docker stop satping || true
        docker rm satping || true
        docker run -d --name satping \
          -e N2YO_API_KEY={{ n2yo_api_key }} \
          {{ ecr_image }}
