---
- name: Configure SatPing server
  hosts: satping
  become: yes

  tasks:
    - name: Update all packages
      dnf:
        name: "*"
        state: latest

    - name: Install Docker
      dnf:
        name: docker
        state: present

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
