name: SatPing CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t satping .

      - name: Test Docker image starts correctly
        env:
          N2YO_API_KEY: ${{ secrets.N2YO_API_KEY }}
        run: |
          docker run -d --name satping -e N2YO_API_KEY=$N2YO_API_KEY satping
          sleep 15
          docker logs satping
          docker stop satping